### ISSUE TITLE
Anyway to submit source files also

### ISSUE THREAD

**Issue by AXeL-dev** [fregante/web-ext-submit#2]
Hey,

I'm currently using this tool to submit some of my extensions to [AMO](https://addons.mozilla.org), & i was wondering if source files can also be submited using something like:
```bash
web-ext-submit --source-files-zip=sources.zip
```
Thanks in advance.

**Comment by fregante** [comment]
Hi, unfortunately the API doesn't support it. Refer to https://github.com/mozilla/addons/issues/6158

**Comment by hyzyla** [comment]
As workaround for now, we can use update method:

```
git archive -o source.zip HEAD
curl -XPATCH "https://addons.mozilla.org/api/v5/addons/addon/<add-on id>/versions/<version-id>/"  \
  -H "Authorization: <JWT blob>" \
  -F "source=@source.zip" -F "license=MPL-2.0"
```
