### ISSUE TITLE
Add WEB_EXT_ID to update Firefox extension

### ISSUE THREAD

**Issue by carlosdanna** [fregante/web-ext-submit#3]
Hi @fregante is there a way for the script to take the `WEB_EXT_ID` env variable so when deploying to firefox addons we don't create a new extension every time but update the existing one.

Here is mentioned in the command line documentation under web-ext sign.
https://extensionworkshop.com/documentation/develop/web-ext-command-reference/

It would be great if we could set it up this way. 

By the way great job with all your projects I've been using them to create our current browser extensions. Thanks for sharing

**Comment by fregante** [comment]
ENV variables are automatically handled by `web-ext`. What works for `web-ext` also works for this. 

In my extensions I just set the ID under applications.gecko in manifest.json. Chrome will complain during development but it’s fine, it’s not a real problem.
