### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by janrito** [fregante/web-ext-submit#4]
I can't find much documentatino of how this works, but asking here jsut in case.

Submitted add-ons by default signal compatibility with both desktop firefox and firefox for android. Is there a way to limit that to just the desktop for example?

**Comment by fregante** [comment]
You can find this setting on the Developer Hub after upload: https://addons.mozilla.org/en-us/developers/

This tool exclusively uploads the files using `web-ext sign`  https://extensionworkshop.com/documentation/develop/web-ext-command-reference/
